### ISSUE TITLE
Reference to a missing lesson

### ISSUE THREAD

**Issue by ragekit** [scratchapixel/website#21]
In the intro to global illumination and path tracing, there is a reference to a lesson on the rendering equation that does not seem to exists.
Screenshot for the passage 
![image](https://user-images.githubusercontent.com/278505/211173212-3129ec15-e249-4bfb-8102-875110a2b69c.png)

**Comment by ragekit** [comment]
![Uploading Screenshot_20230107-234709.png…]()

**Comment by scratchapixel** [comment]
Removed the reference in the lesson.

**Comment by scratchapixel** [comment]
Removed the reference in the lesson.
